# -*- coding: mbcs -*-
from part import *
from material import *
from section import *
from assembly import *
from step import *
from interaction import *
from load import *
from mesh import *
from optimization import *
from job import *
from sketch import *
from visualization import *
from connectorBehavior import *
mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=200.0)
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(0.0, 0.0), point2=(
    0.0, 21.8))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[2])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(0.0, 21.8), point2=(
    0.0, 37.95))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[3])
mdb.models['Model-1'].sketches['__profile__'].ParallelConstraint(addUndoState=
    False, entity1=mdb.models['Model-1'].sketches['__profile__'].geometry[2], 
    entity2=mdb.models['Model-1'].sketches['__profile__'].geometry[3])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(0.0, 0.0), point2=(
    0.0, -21.8))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[4])
mdb.models['Model-1'].sketches['__profile__'].ParallelConstraint(addUndoState=
    False, entity1=mdb.models['Model-1'].sketches['__profile__'].geometry[2], 
    entity2=mdb.models['Model-1'].sketches['__profile__'].geometry[4])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(0.0, -21.8), point2=
    (0.0, -37.95))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[5])
mdb.models['Model-1'].sketches['__profile__'].ParallelConstraint(addUndoState=
    False, entity1=mdb.models['Model-1'].sketches['__profile__'].geometry[4], 
    entity2=mdb.models['Model-1'].sketches['__profile__'].geometry[5])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(0.0, 37.95), point2=
    (53.95, 37.95))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[6])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[6])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(0.0, 37.95), point2=
    (-53.95, 37.95))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[7])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[3], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[7])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(0.0, -37.95), 
    point2=(53.95, -37.95))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[8])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[5], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[8])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(0.0, -37.95), 
    point2=(-53.95, -37.95))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[9])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[5], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[9])
mdb.models['Model-1'].sketches['__profile__'].CircleByCenterPerimeter(center=(
    -53.95, 34.95), point1=(-53.95, 37.95))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-53.95, 34.95), 
    point2=(-56.95, 34.95))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[11])
mdb.models['Model-1'].sketches['__profile__'].CoincidentConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].vertices[10], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[10])
mdb.models['Model-1'].sketches['__profile__'].breakCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[10], curve2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[11], point1=(
    -54.6662406921387, 32.6842269897461), point2=(-55.3110313415527, 
    35.0740623474121))
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[13], ))
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[11], ))
mdb.models['Model-1'].sketches['__profile__'].CircleByCenterPerimeter(center=(
    -53.95, -34.95), point1=(-53.95, -37.95))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-53.95, -34.95), 
    point2=(-56.95, -34.95))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[15])
mdb.models['Model-1'].sketches['__profile__'].CoincidentConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].vertices[12], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[14])
mdb.models['Model-1'].sketches['__profile__'].breakCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[14], curve2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[15], point1=(
    -56.834587097168, -37.5181121826172), point2=(-55.2094573974609, 
    -35.3890113830566))
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[16], ))
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[15], ))
mdb.models['Model-1'].sketches['__profile__'].CircleByCenterPerimeter(center=(
    53.95, 34.95), point1=(53.95, 37.95))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(53.95, 34.95), 
    point2=(56.95, 34.95))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[19])
mdb.models['Model-1'].sketches['__profile__'].CoincidentConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].vertices[14], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[18])
mdb.models['Model-1'].sketches['__profile__'].breakCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[18], curve2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[19], point1=(
    54.4764976501465, 31.5016136169434), point2=(54.9246559143066, 
    34.8566970825195))
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[20], ))
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[19], ))
mdb.models['Model-1'].sketches['__profile__'].CircleByCenterPerimeter(center=(
    53.95, -34.95), point1=(53.95, -37.95))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(53.95, -34.95), 
    point2=(56.95, -34.95))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[23])
mdb.models['Model-1'].sketches['__profile__'].CoincidentConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].vertices[16], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[22])
mdb.models['Model-1'].sketches['__profile__'].breakCurve(curve1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[22], curve2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[23], point1=(
    52.1236839294434, -32.133056640625), point2=(55.2607917785645, 
    -35.1526260375977))
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[25], ))
mdb.models['Model-1'].sketches['__profile__'].delete(objectList=(
    mdb.models['Model-1'].sketches['__profile__'].geometry[23], ))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(56.95, 34.95), 
    point2=(56.95, -34.95))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[26])
mdb.models['Model-1'].sketches['__profile__'].TangentConstraint(addUndoState=
    False, entity1=mdb.models['Model-1'].sketches['__profile__'].geometry[21], 
    entity2=mdb.models['Model-1'].sketches['__profile__'].geometry[26])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-56.95, 34.95), 
    point2=(-56.95, -34.95))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[27])
mdb.models['Model-1'].sketches['__profile__'].TangentConstraint(addUndoState=
    False, entity1=mdb.models['Model-1'].sketches['__profile__'].geometry[12], 
    entity2=mdb.models['Model-1'].sketches['__profile__'].geometry[27])
mdb.models['Model-1'].Part(dimensionality=THREE_D, name='Profile_shell', type=
    DEFORMABLE_BODY)
mdb.models['Model-1'].parts['Profile_shell'].BaseShellExtrude(depth=430.0, 
    sketch=mdb.models['Model-1'].sketches['__profile__'])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].ConstrainedSketch(gridSpacing=21.75, name='__profile__', 
    sheetSize=870.05, transform=
    mdb.models['Model-1'].parts['Profile_shell'].MakeSketchTransform(
    sketchPlane=mdb.models['Model-1'].parts['Profile_shell'].faces[1], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['Model-1'].parts['Profile_shell'].edges[11], 
    sketchOrientation=RIGHT, origin=(-26.975, 37.95, 215.0)))
mdb.models['Model-1'].parts['Profile_shell'].projectReferencesOntoSketch(
    filter=COPLANAR_EDGES, sketch=
    mdb.models['Model-1'].sketches['__profile__'])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-26.975, 215.0), 
    point2=(-80.93, 205.085))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-26.975, 215.0), 
    point2=(26.98, 205.09))
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].ConstrainedSketch(gridSpacing=21.75, name='__profile__', 
    sheetSize=870.05, transform=
    mdb.models['Model-1'].parts['Profile_shell'].MakeSketchTransform(
    sketchPlane=mdb.models['Model-1'].parts['Profile_shell'].faces[1], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['Model-1'].parts['Profile_shell'].edges[12], 
    sketchOrientation=RIGHT, origin=(-26.975, 37.95, 215.0)))
mdb.models['Model-1'].parts['Profile_shell'].projectReferencesOntoSketch(
    filter=COPLANAR_EDGES, sketch=
    mdb.models['Model-1'].sketches['__profile__'])
mdb.models['Model-1'].sketches['__profile__'].Spot(point=(-205.085, 80.93))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-215.0, 26.975), 
    point2=(-205.085, 80.93))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-205.085, 80.93), 
    point2=(-201.297025135253, 101.543230844662))
mdb.models['Model-1'].sketches['__profile__'].ParallelConstraint(addUndoState=
    False, entity1=mdb.models['Model-1'].sketches['__profile__'].geometry[13], 
    entity2=mdb.models['Model-1'].sketches['__profile__'].geometry[14])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-215.0, 26.975), 
    point2=(-215.0, 100.27607879648))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[15])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[2], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[15])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-215.0, 
    100.27607879648), point2=(-201.297025135253, 101.543230844662))
mdb.models['Model-1'].parts['Profile_shell'].CutExtrude(flipExtrudeDirection=ON
    , sketch=mdb.models['Model-1'].sketches['__profile__'], sketchOrientation=
    RIGHT, sketchPlane=mdb.models['Model-1'].parts['Profile_shell'].faces[1], 
    sketchPlaneSide=SIDE1, sketchUpEdge=
    mdb.models['Model-1'].parts['Profile_shell'].edges[12])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].ConstrainedSketch(gridSpacing=21.66, name='__profile__', 
    sheetSize=866.74, transform=
    mdb.models['Model-1'].parts['Profile_shell'].MakeSketchTransform(
    sketchPlane=mdb.models['Model-1'].parts['Profile_shell'].faces[2], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['Model-1'].parts['Profile_shell'].edges[14], 
    sketchOrientation=RIGHT, origin=(-26.975, 37.95, 215.0)))
mdb.models['Model-1'].parts['Profile_shell'].projectReferencesOntoSketch(
    filter=COPLANAR_EDGES, sketch=
    mdb.models['Model-1'].sketches['__profile__'])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-26.975, -215.0), 
    point2=(26.98, -205.085))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(26.98, -205.085), 
    point2=(92.0550000007823, -193.126541562275))
mdb.models['Model-1'].sketches['__profile__'].ParallelConstraint(addUndoState=
    False, entity1=mdb.models['Model-1'].sketches['__profile__'].geometry[13], 
    entity2=mdb.models['Model-1'].sketches['__profile__'].geometry[14])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(92.0550000007823, 
    -193.126541562275), point2=(92.0550000007823, -220.851257324219))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[15])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(92.0550000007823, 
    -220.851257324219), point2=(26.975, -215.0))
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(26.975, -215.0), 
    point2=(-26.975, -215.0))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[17])
mdb.models['Model-1'].sketches['__profile__'].ParallelConstraint(addUndoState=
    False, entity1=mdb.models['Model-1'].sketches['__profile__'].geometry[7], 
    entity2=mdb.models['Model-1'].sketches['__profile__'].geometry[17])
mdb.models['Model-1'].parts['Profile_shell'].CutExtrude(flipExtrudeDirection=ON
    , sketch=mdb.models['Model-1'].sketches['__profile__'], sketchOrientation=
    RIGHT, sketchPlane=mdb.models['Model-1'].parts['Profile_shell'].faces[2], 
    sketchPlaneSide=SIDE1, sketchUpEdge=
    mdb.models['Model-1'].parts['Profile_shell'].edges[14])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].ConstrainedSketch(gridSpacing=21.99, name='__profile__', 
    sheetSize=879.93, transform=
    mdb.models['Model-1'].parts['Profile_shell'].MakeSketchTransform(
    sketchPlane=mdb.models['Model-1'].parts['Profile_shell'].faces[5], 
    sketchPlaneSide=SIDE1, 
    sketchUpEdge=mdb.models['Model-1'].parts['Profile_shell'].edges[23], 
    sketchOrientation=RIGHT, origin=(0.0, 0.0, 215.0)))
mdb.models['Model-1'].parts['Profile_shell'].projectReferencesOntoSketch(
    filter=COPLANAR_EDGES, sketch=
    mdb.models['Model-1'].sketches['__profile__'])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-21.8, 215.0), 
    point2=(-21.8, -215.0))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[16])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[4], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[16])
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(21.8, 215.0), 
    point2=(21.8, -215.0))
mdb.models['Model-1'].sketches['__profile__'].VerticalConstraint(addUndoState=
    False, entity=mdb.models['Model-1'].sketches['__profile__'].geometry[17])
mdb.models['Model-1'].sketches['__profile__'].PerpendicularConstraint(
    addUndoState=False, entity1=
    mdb.models['Model-1'].sketches['__profile__'].geometry[11], entity2=
    mdb.models['Model-1'].sketches['__profile__'].geometry[17])
mdb.models['Model-1'].parts['Profile_shell'].PartitionFaceBySketch(faces=
    mdb.models['Model-1'].parts['Profile_shell'].faces.getSequenceFromMask((
    '[#20 ]', ), ), sketch=mdb.models['Model-1'].sketches['__profile__'], 
    sketchUpEdge=mdb.models['Model-1'].parts['Profile_shell'].edges[23])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].parts['Profile_shell'].Set(edges=
    mdb.models['Model-1'].parts['Profile_shell'].edges.getSequenceFromMask((
    '[#40a24400 #512 ]', ), ), name='CLAMPED')
mdb.models['Model-1'].parts['Profile_shell'].Set(faces=
    mdb.models['Model-1'].parts['Profile_shell'].faces.getSequenceFromMask((
    '[#1fff ]', ), ), name='Whole')
mdb.models['Model-1'].Material(name='C28')
mdb.models['Model-1'].HomogeneousShellSection(idealization=NO_IDEALIZATION, 
    integrationRule=SIMPSON, material='C28', name='Inner_middle_wall', 
    nodalThicknessField='', numIntPts=5, poissonDefinition=DEFAULT, 
    preIntegrate=OFF, temperature=GRADIENT, thickness=1.5, thicknessField='', 
    thicknessModulus=None, thicknessType=UNIFORM, useDensity=OFF)
mdb.models['Model-1'].HomogeneousShellSection(idealization=NO_IDEALIZATION, 
    integrationRule=SIMPSON, material='C28', name='Side_inner_wall', 
    nodalThicknessField='', numIntPts=5, poissonDefinition=DEFAULT, 
    preIntegrate=OFF, temperature=GRADIENT, thickness=2.0, thicknessField='', 
    thicknessModulus=None, thicknessType=UNIFORM, useDensity=OFF)
mdb.models['Model-1'].HomogeneousShellSection(idealization=NO_IDEALIZATION, 
    integrationRule=SIMPSON, material='C28', name='Outer_wall', 
    nodalThicknessField='', numIntPts=5, poissonDefinition=DEFAULT, 
    preIntegrate=OFF, temperature=GRADIENT, thickness=2.7, thicknessField='', 
    thicknessModulus=None, thicknessType=UNIFORM, useDensity=OFF)
mdb.models['Model-1'].parts['Profile_shell'].Set(faces=
    mdb.models['Model-1'].parts['Profile_shell'].faces.getSequenceFromMask((
    '[#80 ]', ), ), name='Inner_middle')
mdb.models['Model-1'].parts['Profile_shell'].Set(faces=
    mdb.models['Model-1'].parts['Profile_shell'].faces.getSequenceFromMask((
    '[#3 ]', ), ), name='Side_inner')
mdb.models['Model-1'].parts['Profile_shell'].Set(faces=
    mdb.models['Model-1'].parts['Profile_shell'].faces.getSequenceFromMask((
    '[#1f7c ]', ), ), name='Outer')
mdb.models['Model-1'].parts['Profile_shell'].SectionAssignment(offset=0.0, 
    offsetField='', offsetType=MIDDLE_SURFACE, region=
    mdb.models['Model-1'].parts['Profile_shell'].sets['Inner_middle'], 
    sectionName='Inner_middle_wall', thicknessAssignment=FROM_SECTION)
mdb.models['Model-1'].parts['Profile_shell'].SectionAssignment(offset=0.0, 
    offsetField='', offsetType=MIDDLE_SURFACE, region=
    mdb.models['Model-1'].parts['Profile_shell'].sets['Side_inner'], 
    sectionName='Side_inner_wall', thicknessAssignment=FROM_SECTION)
mdb.models['Model-1'].parts['Profile_shell'].SectionAssignment(offset=0.0, 
    offsetField='', offsetType=MIDDLE_SURFACE, region=
    mdb.models['Model-1'].parts['Profile_shell'].sets['Outer'], sectionName=
    'Outer_wall', thicknessAssignment=FROM_SECTION)
mdb.models['Model-1'].ConstrainedSketch(name='__profile__', sheetSize=200.0)
mdb.models['Model-1'].sketches['__profile__'].Line(point1=(-100.0, 0.0), 
    point2=(100.0, 0.0))
mdb.models['Model-1'].sketches['__profile__'].HorizontalConstraint(
    addUndoState=False, entity=
    mdb.models['Model-1'].sketches['__profile__'].geometry[2])
mdb.models['Model-1'].Part(dimensionality=THREE_D, name='Plate_impactor', type=
    ANALYTIC_RIGID_SURFACE)
mdb.models['Model-1'].parts['Plate_impactor'].AnalyticRigidSurfExtrude(depth=
    1.0, sketch=mdb.models['Model-1'].sketches['__profile__'])
del mdb.models['Model-1'].sketches['__profile__']
mdb.models['Model-1'].parts['Plate_impactor'].features['3D Analytic rigid shell-1'].setValues(
    depth=200.0)
mdb.models['Model-1'].parts['Plate_impactor'].regenerate()
mdb.models['Model-1'].parts['Plate_impactor'].ReferencePoint(point=
    mdb.models['Model-1'].parts['Plate_impactor'].InterestingPoint(
    mdb.models['Model-1'].parts['Plate_impactor'].edges[1], MIDDLE))
mdb.models['Model-1'].parts['Plate_impactor'].Set(name='Impactor_rp', 
    referencePoints=(
    mdb.models['Model-1'].parts['Plate_impactor'].referencePoints[2], ))
mdb.models['Model-1'].rootAssembly.DatumCsysByDefault(CARTESIAN)
mdb.models['Model-1'].rootAssembly.Instance(dependent=ON, name=
    'Profile_shell-1', part=mdb.models['Model-1'].parts['Profile_shell'])
mdb.models['Model-1'].rootAssembly.Instance(dependent=ON, name=
    'Plate_impactor-1', part=mdb.models['Model-1'].parts['Plate_impactor'])
mdb.models['Model-1'].rootAssembly.rotate(angle=90.0, axisDirection=(1.0, 0.0, 
    0.0), axisPoint=(0.0, 0.0, 0.0), instanceList=('Plate_impactor-1', ))
mdb.models['Model-1'].rootAssembly.translate(instanceList=('Plate_impactor-1', 
    ), vector=(0.0, 0.0, 431.0))
# Save by ben00 on 2024_02_22-12.26.22; build 2022 2021_09_15-19.57.30 176069
from part import *
from material import *
from section import *
from assembly import *
from step import *
from interaction import *
from load import *
from mesh import *
from optimization import *
from job import *
from sketch import *
from visualization import *
from connectorBehavior import *
mdb.models['Model-1'].ExplicitDynamicsStep(improvedDtMethod=ON, name='Load', 
    previous='Initial', timePeriod=0.5)
mdb.models['Model-1'].SmoothStepAmplitude(data=((0.0, 0.0), (0.01, 1.0)), name=
    'Load_amp', timeSpan=STEP)
mdb.models['Model-1'].steps['Load'].setValues(improvedDtMethod=ON, timePeriod=
    0.05)
mdb.models['Model-1'].HistoryOutputRequest(createStepName='Load', name='F-D', 
    numIntervals=100, rebar=EXCLUDE, region=
    mdb.models['Model-1'].rootAssembly.allInstances['Plate_impactor-1'].sets['Impactor_rp']
    , sectionPoints=DEFAULT, variables=('U3', 'RF3'))
mdb.models['Model-1'].DisplacementBC(amplitude=UNSET, createStepName='Initial', 
    distributionType=UNIFORM, fieldName='', localCsys=None, name=
    'Profile_clamped', region=
    mdb.models['Model-1'].rootAssembly.instances['Profile_shell-1'].sets['CLAMPED']
    , u1=SET, u2=SET, u3=SET, ur1=SET, ur2=SET, ur3=SET)
mdb.models['Model-1'].DisplacementBC(amplitude=UNSET, createStepName='Initial', 
    distributionType=UNIFORM, fieldName='', localCsys=None, name=
    'Clamp_impactor', region=
    mdb.models['Model-1'].rootAssembly.instances['Plate_impactor-1'].sets['Impactor_rp']
    , u1=SET, u2=SET, u3=UNSET, ur1=SET, ur2=SET, ur3=UNSET)
mdb.models['Model-1'].VelocityBC(amplitude='Load_amp', createStepName='Load', 
    distributionType=UNIFORM, fieldName='', localCsys=None, name='BC-3', 
    region=
    mdb.models['Model-1'].rootAssembly.instances['Plate_impactor-1'].sets['Impactor_rp']
    , v1=UNSET, v2=UNSET, v3=-1500.0, vr1=UNSET, vr2=UNSET, vr3=UNSET)
mdb.models['Model-1'].ContactProperty('Interaction')
mdb.models['Model-1'].interactionProperties['Interaction'].NormalBehavior(
    allowSeparation=ON, constraintEnforcementMethod=DEFAULT, 
    pressureOverclosure=HARD)
mdb.models['Model-1'].interactionProperties['Interaction'].TangentialBehavior(
    dependencies=0, directionality=ISOTROPIC, elasticSlipStiffness=None, 
    formulation=PENALTY, fraction=0.005, maximumElasticSlip=FRACTION, 
    pressureDependency=OFF, shearStressLimit=None, slipRateDependency=OFF, 
    table=((0.05, ), ), temperatureDependency=OFF)
mdb.models['Model-1'].ContactExp(createStepName='Load', name='Interaction')
mdb.models['Model-1'].interactions['Interaction'].includedPairs.setValuesInStep(
    stepName='Load', useAllstar=ON)
mdb.models['Model-1'].interactions['Interaction'].contactPropertyAssignments.appendInStep(
    assignments=((GLOBAL, SELF, 'Interaction'), ), stepName='Load')
mdb.models['Model-1'].parts['Plate_impactor'].Surface(name='Surf-1', 
    side1Faces=
    mdb.models['Model-1'].parts['Plate_impactor'].faces.getSequenceFromMask((
    '[#1 ]', ), ))
mdb.models['Model-1'].rootAssembly.regenerate()
mdb.models['Model-1'].fieldOutputRequests['F-Output-1'].setValues(variables=(
    'MISES', 'PEEQ', 'LE', 'U', 'SDV', 'STATUS'))
# Save by ben00 on 2024_02_22-13.44.17; build 2022 2021_09_15-19.57.30 176069
